name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tennis-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - name: Build Angular App
        run: npm run build -- --configuration production
      - name: Upload Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist/tennis-frontend

  backend:
    name: Backend Test & Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - name: Run Tests
        run: npm test
      - name: Run Coverage
        run: npm run test:coverage
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: coverage
      - name: Check Coverage Threshold
        run: |
          npx nyc check-coverage --lines 90 --functions 90 --branches 90

  performance:
    name: k6 Performance Tests
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    defaults:
      run:
        working-directory: k6-tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup k6
        uses: grafana/setup-k6@v1
      - name: Run Ramp Test
        run: k6 run ramp.js --out json=ramp.json
      - name: Run Spike Test
        run: k6 run spike.js --out json=spike.json
      - name: Run Soak Test
        run: k6 run soak.js --out json=soak.json
      - name: Upload k6 Reports
        uses: actions/upload-artifact@v4
        with:
          name: k6-reports
          path: "*.json"
