name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tennis-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build:prod

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROYECTOTENNIS_6B63B }}
          channelId: live
          projectId: proyectotennis-6b63b
          entryPoint: tennis-frontend
